#!/usr/bin/env python3
"""Regenerate client/js/protocol.js from server/nightcord/protocol.py.

    cd server && python tools/gen_client_protocol.py

tests/test_protocol_sync.py checks the result against docs/PROTOCOL.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "server"))

from nightcord import protocol as P  # noqa: E402

OUT = ROOT / "client" / "js" / "protocol.js"


def main() -> None:
    types = [
        (k, v) for k, v in vars(P).items()
        if k.isupper() and isinstance(v, str) and ("." in v or v == "error") and k != "PROTOCOL_VERSION"
    ]
    codes = sorted((k, v) for k, v in vars(P).items() if isinstance(v, str) and v in P.ERROR_CODES and k.isupper())
    lines = [
        "// Wire-format constants. GENERATED by server/tools/gen_client_protocol.py from",
        "// server/nightcord/protocol.py — edit that file, then regenerate. Both follow",
        "// docs/PROTOCOL.md; server/tests/test_protocol_sync.py checks all three agree.",
        "",
        f'export const PROTOCOL_VERSION = "{P.PROTOCOL_VERSION}";',
        "",
        "export const T = Object.freeze({",
        *[f'  {k}: "{v}",' for k, v in types],
        "});",
        "",
        "export const ERR = Object.freeze({",
        *[f'  {k}: "{v}",' for k, v in codes],
        "  // Client-side only: the socket closed before a response arrived.",
        '  DISCONNECTED: "disconnected",',
        '  TIMEOUT: "timeout",',
        "});",
        "",
        "// Permission bits (PROTOCOL.md §5a).",
        "export const PERMS = Object.freeze({",
        *[f"  {k}: {v}," for k, v in P.PERMS.items()],
        "});",
        "",
        "// Requests answered with auth.ok / auth.error rather than X.result / X.error.",
        "export const AUTH_OK_TYPES = new Set([" + ", ".join(
            f"T.{k}" for k, v in types if v in P.AUTH_OK_TYPES) + "]);",
        "",
        "export const LIMITS = Object.freeze({",
        f"  USERNAME_RE: /{P.USERNAME_RE.pattern}/,",
        f"  PASSWORD_MIN_BYTES: {P.PASSWORD_MIN_BYTES},",
        f"  PASSWORD_MAX_BYTES: {P.PASSWORD_MAX_BYTES},",
        f"  CONTENT_MAX_CHARS: {P.CONTENT_MAX_CHARS},",
        f"  GUILD_NAME_MAX: {P.GUILD_NAME_MAX},",
        f"  SERVER_NAME_MAX: {P.SERVER_NAME_MAX},",
        f"  CHANNEL_NAME_RE: /{P.CHANNEL_NAME_RE.pattern}/,",
        f"  HISTORY_PAGE: {P.HISTORY_DEFAULT_LIMIT},",
        f"  DISPLAY_NAME_MAX: {P.DISPLAY_NAME_MAX},",
        f"  BIO_MAX: {P.BIO_MAX},",
        f"  CUSTOM_STATUS_MAX: {P.CUSTOM_STATUS_MAX},",
        f"  ROLE_NAME_MAX: {P.ROLE_NAME_MAX},",
        f"  MAX_REACTION_EMOJI: {P.MAX_REACTION_EMOJI},",
        f"  AVATAR_MAX_BYTES: {P.AVATAR_MAX_BYTES},",
        f"  GROUP_DM_MAX: {P.GROUP_DM_MAX},",
        f"  GROUP_DM_NAME_MAX: {P.GROUP_DM_NAME_MAX},",
        f"  BAN_REASON_MAX: {P.BAN_REASON_MAX},",
        f"  MAX_TIMEOUT_SECONDS: {P.MAX_TIMEOUT_SECONDS},",
        f"  NICKNAME_MAX: {P.NICKNAME_MAX},",
        f"  TOPIC_MAX: {P.TOPIC_MAX},",
        f"  CHANNEL_TITLE_MAX: {P.CHANNEL_TITLE_MAX},",
        f"  MAX_ATTACHMENTS: {P.MAX_ATTACHMENTS},",
        f"  MAX_PINS: {P.MAX_PINS},",
        f"  LEGAL_MAX_CHARS: {P.LEGAL_MAX_CHARS},",
        f"  MAX_MUTE_SECONDS: {P.MAX_MUTE_SECONDS},",
        f"  VANITY_RE: /{P.VANITY_RE.pattern}/,",
        f"  SLOWMODE_PRESETS: Object.freeze([{', '.join(map(str, P.SLOWMODE_PRESETS))}]),",
        f"  INVITE_MAX_USES: Object.freeze([{', '.join(map(str, P.INVITE_MAX_USES))}]),",
        f"  INVITE_MAX_AGES: Object.freeze([{', '.join(map(str, P.INVITE_MAX_AGES))}]),",
        f"  SYSTEM_JOIN: {P.SYSTEM_JOIN},",
        f"  SYSTEM_LEAVE: {P.SYSTEM_LEAVE},",
        f"  EMOJI_NAME_RE: /{P.EMOJI_NAME_RE.pattern}/,",
        f"  MAX_GUILD_EMOJI: {P.MAX_GUILD_EMOJI},",
        f"  MAX_GUILD_STICKERS: {P.MAX_GUILD_STICKERS},",
        f"  STICKER_NAME_MAX: {P.STICKER_NAME_MAX},",
        f"  STICKER_DESCRIPTION_MAX: {P.STICKER_DESCRIPTION_MAX},",
        f"  MAX_ROLE_COLORS: {P.MAX_ROLE_COLORS},",
        "  MEDIA_KINDS: Object.freeze({" + ", ".join(
            f"{k}: Object.freeze({{ maxBytes: {b}, maxDim: {'null' if d is None else d} }})"
            for k, (b, d) in P.MEDIA_KINDS.items()) + "}),",
        "  CUSTOMIZATION_FEATURES: Object.freeze([" + ", ".join(f'"{f}"' for f in P.CUSTOMIZATION_FEATURES) + "]),",
        "  DM_PRIVACY: Object.freeze([" + ", ".join(f'"{f}"' for f in P.DM_PRIVACY) + "]),",
        "  USER_SEARCH_MODES: Object.freeze([" + ", ".join(f'"{f}"' for f in P.USER_SEARCH_MODES) + "]),",
        f"  ANNOUNCEMENT_MAX_CHARS: {P.ANNOUNCEMENT_MAX_CHARS},",
        f"  MAX_EMBEDS_PER_MESSAGE: {P.MAX_EMBEDS_PER_MESSAGE},",
        f"  MAX_ACCOUNTS_PER_CLIENT: {P.MAX_ACCOUNTS_PER_CLIENT},",
        "});",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
