// Wire-format constants. Mirrors server/nightcord/protocol.py; both are
// implemented against docs/PROTOCOL.md, which wins if they disagree.
// server/tests/test_protocol_sync.py checks all three stay in sync.

export const PROTOCOL_VERSION = "0.2";

export const T = Object.freeze({
  AUTH_REGISTER: "auth.register",
  AUTH_LOGIN: "auth.login",
  AUTH_RESUME: "auth.resume",
  AUTH_REQUEST_ACCOUNT: "auth.request_account",
  AUTH_REQUEST_ACCOUNT_RESULT: "auth.request_account.result",
  AUTH_OK: "auth.ok",
  AUTH_ERROR: "auth.error",
  AUTH_LOGOUT: "auth.logout",
  AUTH_LOGOUT_RESULT: "auth.logout.result",
  SERVER_INFO: "server.info",
  SERVER_INFO_RESULT: "server.info.result",
  SERVER_CONFIG_UPDATE: "server.config.update",
  SERVER_CONFIG_UPDATE_RESULT: "server.config.update.result",
  GUILD_LIST: "guild.list",
  GUILD_LIST_RESULT: "guild.list.result",
  GUILD_CREATE: "guild.create",
  GUILD_CREATE_RESULT: "guild.create.result",
  GUILD_PUBLIC_LIST: "guild.public_list",
  GUILD_PUBLIC_LIST_RESULT: "guild.public_list.result",
  GUILD_JOIN_BY_CODE: "guild.join_by_code",
  GUILD_JOIN_BY_CODE_RESULT: "guild.join_by_code.result",
  GUILD_JOIN_BY_ID: "guild.join_by_id",
  GUILD_JOIN_BY_ID_RESULT: "guild.join_by_id.result",
  GUILD_OWNER_OVERRIDE_JOIN: "guild.owner_override_join",
  GUILD_OWNER_OVERRIDE_JOIN_RESULT: "guild.owner_override_join.result",
  GUILD_LEAVE: "guild.leave",
  GUILD_LEAVE_RESULT: "guild.leave.result",
  GUILD_MEMBERS: "guild.members",
  GUILD_MEMBERS_RESULT: "guild.members.result",
  GUILD_CONFIG_UPDATE: "guild.config.update",
  GUILD_CONFIG_UPDATE_RESULT: "guild.config.update.result",
  GUILD_INVITE_CREATE: "guild.invite.create",
  GUILD_INVITE_CREATE_RESULT: "guild.invite.create.result",
  GUILD_UPDATED: "guild.updated",
  GUILD_MEMBER_JOINED: "guild.member_joined",
  GUILD_MEMBER_LEFT: "guild.member_left",
  CHANNEL_LIST: "channel.list",
  CHANNEL_LIST_RESULT: "channel.list.result",
  CHANNEL_JOIN: "channel.join",
  CHANNEL_JOIN_RESULT: "channel.join.result",
  CHANNEL_LEAVE: "channel.leave",
  CHANNEL_LEAVE_RESULT: "channel.leave.result",
  CHANNEL_HISTORY: "channel.history",
  CHANNEL_HISTORY_RESULT: "channel.history.result",
  CHANNEL_CREATE: "channel.create",
  CHANNEL_CREATE_RESULT: "channel.create.result",
  CHANNEL_UPDATE: "channel.update",
  CHANNEL_UPDATE_RESULT: "channel.update.result",
  CHANNEL_DELETE: "channel.delete",
  CHANNEL_DELETE_RESULT: "channel.delete.result",
  CHANNEL_CREATED: "channel.created",
  CHANNEL_UPDATED: "channel.updated",
  CHANNEL_DELETED: "channel.deleted",
  MESSAGE_SEND: "message.send",
  MESSAGE_SEND_RESULT: "message.send.result",
  MESSAGE_NEW: "message.new",
  PRESENCE_LIST: "presence.list",
  PRESENCE_LIST_RESULT: "presence.list.result",
  PRESENCE_UPDATE: "presence.update",
  ERROR: "error",
});

export const ERR = Object.freeze({
  ALREADY_MEMBER: "already_member",
  BAD_REQUEST: "bad_request",
  CONTENT_TOO_LONG: "content_too_long",
  FORBIDDEN: "forbidden",
  GUILD_CREATION_DISABLED: "guild_creation_disabled",
  INTERNAL_ERROR: "internal_error",
  INVALID_CREDENTIALS: "invalid_credentials",
  INVALID_PASSWORD: "invalid_password",
  INVALID_USERNAME: "invalid_username",
  INVITE_INVALID: "invite_invalid",
  NOT_AUTHENTICATED: "not_authenticated",
  NOT_FOUND: "not_found",
  RATE_LIMITED: "rate_limited",
  REGISTRATION_CLOSED: "registration_closed",
  REGISTRATION_PENDING_APPROVAL: "registration_pending_approval",
  SESSION_EXPIRED: "session_expired",
  UNKNOWN_TYPE: "unknown_type",
  USERNAME_TAKEN: "username_taken",
  // Client-side only: the socket closed before a response arrived.
  DISCONNECTED: "disconnected",
  TIMEOUT: "timeout",
});

// Requests answered with auth.ok / auth.error rather than X.result / X.error.
export const AUTH_OK_TYPES = new Set([T.AUTH_REGISTER, T.AUTH_LOGIN, T.AUTH_RESUME]);

export const LIMITS = Object.freeze({
  USERNAME_RE: /^[A-Za-z0-9_.-]{3,32}$/,
  PASSWORD_MIN_BYTES: 8,
  PASSWORD_MAX_BYTES: 72,
  CONTENT_MAX_CHARS: 2000,
  GUILD_NAME_MAX: 100,
  CHANNEL_NAME_RE: /^[a-z0-9_-]{1,32}$/,
  HISTORY_PAGE: 50,
});
