// Country flag emoji: every ISO 3166-1 alpha-2 code, built at load time from
// its two regional-indicator letters, plus the three subdivision flags
// (England, Scotland, Wales) that need a tag sequence, and the handful of
// generic flags.
//
// The data lives in this module, not a JSON file: the standalone single-file
// build (client/scripts/build-standalone.mjs) can't fetch anything at runtime.
//
// Whether a flag actually draws is up to the reader's font — Windows has no
// country flag glyphs, so those show the two letters instead. That's a
// platform thing, not something the client can fix.

// [code, name, keywords]. The first keyword is the :shortcode:.
const COUNTRIES = [
  ["AD", "Andorra", "flag_ad andorra ad flag"],
  ["AE", "United Arab Emirates", "flag_ae united_arab_emirates uae ae flag"],
  ["AF", "Afghanistan", "flag_af afghanistan af flag"],
  ["AG", "Antigua and Barbuda", "flag_ag antigua_and_barbuda ag flag"],
  ["AI", "Anguilla", "flag_ai anguilla ai flag"],
  ["AL", "Albania", "flag_al albania al flag"],
  ["AM", "Armenia", "flag_am armenia am flag"],
  ["AO", "Angola", "flag_ao angola ao flag"],
  ["AQ", "Antarctica", "flag_aq antarctica aq flag"],
  ["AR", "Argentina", "flag_ar argentina ar flag"],
  ["AS", "American Samoa", "flag_as american_samoa as flag"],
  ["AT", "Austria", "flag_at austria at flag"],
  ["AU", "Australia", "flag_au australia aussie au flag"],
  ["AW", "Aruba", "flag_aw aruba aw flag"],
  ["AX", "Aland Islands", "flag_ax aland_islands ax flag"],
  ["AZ", "Azerbaijan", "flag_az azerbaijan az flag"],
  ["BA", "Bosnia and Herzegovina", "flag_ba bosnia_and_herzegovina ba flag"],
  ["BB", "Barbados", "flag_bb barbados bb flag"],
  ["BD", "Bangladesh", "flag_bd bangladesh bd flag"],
  ["BE", "Belgium", "flag_be belgium be flag"],
  ["BF", "Burkina Faso", "flag_bf burkina_faso bf flag"],
  ["BG", "Bulgaria", "flag_bg bulgaria bg flag"],
  ["BH", "Bahrain", "flag_bh bahrain bh flag"],
  ["BI", "Burundi", "flag_bi burundi bi flag"],
  ["BJ", "Benin", "flag_bj benin bj flag"],
  ["BL", "Saint Barthelemy", "flag_bl saint_barthelemy bl flag"],
  ["BM", "Bermuda", "flag_bm bermuda bm flag"],
  ["BN", "Brunei", "flag_bn brunei bn flag"],
  ["BO", "Bolivia", "flag_bo bolivia bo flag"],
  ["BQ", "Caribbean Netherlands", "flag_bq caribbean_netherlands bq flag"],
  ["BR", "Brazil", "flag_br brazil br flag"],
  ["BS", "Bahamas", "flag_bs bahamas bs flag"],
  ["BT", "Bhutan", "flag_bt bhutan bt flag"],
  ["BV", "Bouvet Island", "flag_bv bouvet_island bv flag"],
  ["BW", "Botswana", "flag_bw botswana bw flag"],
  ["BY", "Belarus", "flag_by belarus by flag"],
  ["BZ", "Belize", "flag_bz belize bz flag"],
  ["CA", "Canada", "flag_ca canada ca flag"],
  ["CC", "Cocos Islands", "flag_cc cocos_islands cc flag"],
  ["CD", "Congo Kinshasa", "flag_cd congo_kinshasa drc cd flag"],
  ["CF", "Central African Republic", "flag_cf central_african_republic cf flag"],
  ["CG", "Congo Brazzaville", "flag_cg congo_brazzaville cg flag"],
  ["CH", "Switzerland", "flag_ch switzerland swiss ch flag"],
  ["CI", "Cote d Ivoire", "flag_ci cote_d_ivoire ivory_coast ci flag"],
  ["CK", "Cook Islands", "flag_ck cook_islands ck flag"],
  ["CL", "Chile", "flag_cl chile cl flag"],
  ["CM", "Cameroon", "flag_cm cameroon cm flag"],
  ["CN", "China", "flag_cn china chinese cn flag"],
  ["CO", "Colombia", "flag_co colombia co flag"],
  ["CR", "Costa Rica", "flag_cr costa_rica cr flag"],
  ["CU", "Cuba", "flag_cu cuba cu flag"],
  ["CV", "Cape Verde", "flag_cv cape_verde cv flag"],
  ["CW", "Curacao", "flag_cw curacao cw flag"],
  ["CX", "Christmas Island", "flag_cx christmas_island cx flag"],
  ["CY", "Cyprus", "flag_cy cyprus cy flag"],
  ["CZ", "Czechia", "flag_cz czechia czech_republic cz flag"],
  ["DE", "Germany", "flag_de germany german deutschland de flag"],
  ["DJ", "Djibouti", "flag_dj djibouti dj flag"],
  ["DK", "Denmark", "flag_dk denmark danish dk flag"],
  ["DM", "Dominica", "flag_dm dominica dm flag"],
  ["DO", "Dominican Republic", "flag_do dominican_republic do flag"],
  ["DZ", "Algeria", "flag_dz algeria dz flag"],
  ["EC", "Ecuador", "flag_ec ecuador ec flag"],
  ["EE", "Estonia", "flag_ee estonia ee flag"],
  ["EG", "Egypt", "flag_eg egypt eg flag"],
  ["EH", "Western Sahara", "flag_eh western_sahara eh flag"],
  ["ER", "Eritrea", "flag_er eritrea er flag"],
  ["ES", "Spain", "flag_es spain spanish espana es flag"],
  ["ET", "Ethiopia", "flag_et ethiopia et flag"],
  ["FI", "Finland", "flag_fi finland finnish fi flag"],
  ["FJ", "Fiji", "flag_fj fiji fj flag"],
  ["FK", "Falkland Islands", "flag_fk falkland_islands fk flag"],
  ["FM", "Micronesia", "flag_fm micronesia fm flag"],
  ["FO", "Faroe Islands", "flag_fo faroe_islands fo flag"],
  ["FR", "France", "flag_fr france french fr flag"],
  ["GA", "Gabon", "flag_ga gabon ga flag"],
  ["GB", "United Kingdom", "flag_gb united_kingdom uk britain british gb flag"],
  ["GD", "Grenada", "flag_gd grenada gd flag"],
  ["GE", "Georgia", "flag_ge georgia ge flag"],
  ["GF", "French Guiana", "flag_gf french_guiana gf flag"],
  ["GG", "Guernsey", "flag_gg guernsey gg flag"],
  ["GH", "Ghana", "flag_gh ghana gh flag"],
  ["GI", "Gibraltar", "flag_gi gibraltar gi flag"],
  ["GL", "Greenland", "flag_gl greenland gl flag"],
  ["GM", "Gambia", "flag_gm gambia gm flag"],
  ["GN", "Guinea", "flag_gn guinea gn flag"],
  ["GP", "Guadeloupe", "flag_gp guadeloupe gp flag"],
  ["GQ", "Equatorial Guinea", "flag_gq equatorial_guinea gq flag"],
  ["GR", "Greece", "flag_gr greece greek gr flag"],
  ["GS", "South Georgia", "flag_gs south_georgia gs flag"],
  ["GT", "Guatemala", "flag_gt guatemala gt flag"],
  ["GU", "Guam", "flag_gu guam gu flag"],
  ["GW", "Guinea Bissau", "flag_gw guinea_bissau gw flag"],
  ["GY", "Guyana", "flag_gy guyana gy flag"],
  ["HK", "Hong Kong", "flag_hk hong_kong hk flag"],
  ["HM", "Heard and McDonald Islands", "flag_hm heard_and_mcdonald_islands hm flag"],
  ["HN", "Honduras", "flag_hn honduras hn flag"],
  ["HR", "Croatia", "flag_hr croatia hr flag"],
  ["HT", "Haiti", "flag_ht haiti ht flag"],
  ["HU", "Hungary", "flag_hu hungary hu flag"],
  ["ID", "Indonesia", "flag_id indonesia id flag"],
  ["IE", "Ireland", "flag_ie ireland irish ie flag"],
  ["IL", "Israel", "flag_il israel il flag"],
  ["IM", "Isle of Man", "flag_im isle_of_man im flag"],
  ["IN", "India", "flag_in india indian in flag"],
  ["IO", "British Indian Ocean Territory", "flag_io british_indian_ocean_territory io flag"],
  ["IQ", "Iraq", "flag_iq iraq iq flag"],
  ["IR", "Iran", "flag_ir iran ir flag"],
  ["IS", "Iceland", "flag_is iceland is flag"],
  ["IT", "Italy", "flag_it italy italian it flag"],
  ["JE", "Jersey", "flag_je jersey je flag"],
  ["JM", "Jamaica", "flag_jm jamaica jm flag"],
  ["JO", "Jordan", "flag_jo jordan jo flag"],
  ["JP", "Japan", "flag_jp japan japanese nippon jp flag"],
  ["KE", "Kenya", "flag_ke kenya ke flag"],
  ["KG", "Kyrgyzstan", "flag_kg kyrgyzstan kg flag"],
  ["KH", "Cambodia", "flag_kh cambodia kh flag"],
  ["KI", "Kiribati", "flag_ki kiribati ki flag"],
  ["KM", "Comoros", "flag_km comoros km flag"],
  ["KN", "Saint Kitts and Nevis", "flag_kn saint_kitts_and_nevis kn flag"],
  ["KP", "North Korea", "flag_kp north_korea kp flag"],
  ["KR", "South Korea", "flag_kr south_korea korea kr flag"],
  ["KW", "Kuwait", "flag_kw kuwait kw flag"],
  ["KY", "Cayman Islands", "flag_ky cayman_islands ky flag"],
  ["KZ", "Kazakhstan", "flag_kz kazakhstan kz flag"],
  ["LA", "Laos", "flag_la laos la flag"],
  ["LB", "Lebanon", "flag_lb lebanon lb flag"],
  ["LC", "Saint Lucia", "flag_lc saint_lucia lc flag"],
  ["LI", "Liechtenstein", "flag_li liechtenstein li flag"],
  ["LK", "Sri Lanka", "flag_lk sri_lanka lk flag"],
  ["LR", "Liberia", "flag_lr liberia lr flag"],
  ["LS", "Lesotho", "flag_ls lesotho ls flag"],
  ["LT", "Lithuania", "flag_lt lithuania lt flag"],
  ["LU", "Luxembourg", "flag_lu luxembourg lu flag"],
  ["LV", "Latvia", "flag_lv latvia lv flag"],
  ["LY", "Libya", "flag_ly libya ly flag"],
  ["MA", "Morocco", "flag_ma morocco ma flag"],
  ["MC", "Monaco", "flag_mc monaco mc flag"],
  ["MD", "Moldova", "flag_md moldova md flag"],
  ["ME", "Montenegro", "flag_me montenegro me flag"],
  ["MF", "Saint Martin", "flag_mf saint_martin mf flag"],
  ["MG", "Madagascar", "flag_mg madagascar mg flag"],
  ["MH", "Marshall Islands", "flag_mh marshall_islands mh flag"],
  ["MK", "North Macedonia", "flag_mk north_macedonia mk flag"],
  ["ML", "Mali", "flag_ml mali ml flag"],
  ["MM", "Myanmar", "flag_mm myanmar burma mm flag"],
  ["MN", "Mongolia", "flag_mn mongolia mn flag"],
  ["MO", "Macau", "flag_mo macau mo flag"],
  ["MP", "Northern Mariana Islands", "flag_mp northern_mariana_islands mp flag"],
  ["MQ", "Martinique", "flag_mq martinique mq flag"],
  ["MR", "Mauritania", "flag_mr mauritania mr flag"],
  ["MS", "Montserrat", "flag_ms montserrat ms flag"],
  ["MT", "Malta", "flag_mt malta mt flag"],
  ["MU", "Mauritius", "flag_mu mauritius mu flag"],
  ["MV", "Maldives", "flag_mv maldives mv flag"],
  ["MW", "Malawi", "flag_mw malawi mw flag"],
  ["MX", "Mexico", "flag_mx mexico mexican mx flag"],
  ["MY", "Malaysia", "flag_my malaysia my flag"],
  ["MZ", "Mozambique", "flag_mz mozambique mz flag"],
  ["NA", "Namibia", "flag_na namibia na flag"],
  ["NC", "New Caledonia", "flag_nc new_caledonia nc flag"],
  ["NE", "Niger", "flag_ne niger ne flag"],
  ["NF", "Norfolk Island", "flag_nf norfolk_island nf flag"],
  ["NG", "Nigeria", "flag_ng nigeria ng flag"],
  ["NI", "Nicaragua", "flag_ni nicaragua ni flag"],
  ["NL", "Netherlands", "flag_nl netherlands holland dutch nl flag"],
  ["NO", "Norway", "flag_no norway norwegian no flag"],
  ["NP", "Nepal", "flag_np nepal np flag"],
  ["NR", "Nauru", "flag_nr nauru nr flag"],
  ["NU", "Niue", "flag_nu niue nu flag"],
  ["NZ", "New Zealand", "flag_nz new_zealand kiwi nz flag"],
  ["OM", "Oman", "flag_om oman om flag"],
  ["PA", "Panama", "flag_pa panama pa flag"],
  ["PE", "Peru", "flag_pe peru pe flag"],
  ["PF", "French Polynesia", "flag_pf french_polynesia pf flag"],
  ["PG", "Papua New Guinea", "flag_pg papua_new_guinea pg flag"],
  ["PH", "Philippines", "flag_ph philippines ph flag"],
  ["PK", "Pakistan", "flag_pk pakistan pk flag"],
  ["PL", "Poland", "flag_pl poland polish pl flag"],
  ["PM", "Saint Pierre and Miquelon", "flag_pm saint_pierre_and_miquelon pm flag"],
  ["PN", "Pitcairn Islands", "flag_pn pitcairn_islands pn flag"],
  ["PR", "Puerto Rico", "flag_pr puerto_rico pr flag"],
  ["PS", "Palestine", "flag_ps palestine ps flag"],
  ["PT", "Portugal", "flag_pt portugal portuguese pt flag"],
  ["PW", "Palau", "flag_pw palau pw flag"],
  ["PY", "Paraguay", "flag_py paraguay py flag"],
  ["QA", "Qatar", "flag_qa qatar qa flag"],
  ["RE", "Reunion", "flag_re reunion re flag"],
  ["RO", "Romania", "flag_ro romania ro flag"],
  ["RS", "Serbia", "flag_rs serbia rs flag"],
  ["RU", "Russia", "flag_ru russia russian ru flag"],
  ["RW", "Rwanda", "flag_rw rwanda rw flag"],
  ["SA", "Saudi Arabia", "flag_sa saudi_arabia sa flag"],
  ["SB", "Solomon Islands", "flag_sb solomon_islands sb flag"],
  ["SC", "Seychelles", "flag_sc seychelles sc flag"],
  ["SD", "Sudan", "flag_sd sudan sd flag"],
  ["SE", "Sweden", "flag_se sweden swedish se flag"],
  ["SG", "Singapore", "flag_sg singapore sg flag"],
  ["SH", "Saint Helena", "flag_sh saint_helena sh flag"],
  ["SI", "Slovenia", "flag_si slovenia si flag"],
  ["SJ", "Svalbard and Jan Mayen", "flag_sj svalbard_and_jan_mayen sj flag"],
  ["SK", "Slovakia", "flag_sk slovakia sk flag"],
  ["SL", "Sierra Leone", "flag_sl sierra_leone sl flag"],
  ["SM", "San Marino", "flag_sm san_marino sm flag"],
  ["SN", "Senegal", "flag_sn senegal sn flag"],
  ["SO", "Somalia", "flag_so somalia so flag"],
  ["SR", "Suriname", "flag_sr suriname sr flag"],
  ["SS", "South Sudan", "flag_ss south_sudan ss flag"],
  ["ST", "Sao Tome and Principe", "flag_st sao_tome_and_principe st flag"],
  ["SV", "El Salvador", "flag_sv el_salvador sv flag"],
  ["SX", "Sint Maarten", "flag_sx sint_maarten sx flag"],
  ["SY", "Syria", "flag_sy syria sy flag"],
  ["SZ", "Eswatini", "flag_sz eswatini swaziland sz flag"],
  ["TC", "Turks and Caicos Islands", "flag_tc turks_and_caicos_islands tc flag"],
  ["TD", "Chad", "flag_td chad td flag"],
  ["TF", "French Southern Territories", "flag_tf french_southern_territories tf flag"],
  ["TG", "Togo", "flag_tg togo tg flag"],
  ["TH", "Thailand", "flag_th thailand thai th flag"],
  ["TJ", "Tajikistan", "flag_tj tajikistan tj flag"],
  ["TK", "Tokelau", "flag_tk tokelau tk flag"],
  ["TL", "Timor Leste", "flag_tl timor_leste east_timor tl flag"],
  ["TM", "Turkmenistan", "flag_tm turkmenistan tm flag"],
  ["TN", "Tunisia", "flag_tn tunisia tn flag"],
  ["TO", "Tonga", "flag_to tonga to flag"],
  ["TR", "Turkiye", "flag_tr turkiye turkey tr flag"],
  ["TT", "Trinidad and Tobago", "flag_tt trinidad_and_tobago tt flag"],
  ["TV", "Tuvalu", "flag_tv tuvalu tv flag"],
  ["TW", "Taiwan", "flag_tw taiwan tw flag"],
  ["TZ", "Tanzania", "flag_tz tanzania tz flag"],
  ["UA", "Ukraine", "flag_ua ukraine ukrainian ua flag"],
  ["UG", "Uganda", "flag_ug uganda ug flag"],
  ["UM", "US Outlying Islands", "flag_um us_outlying_islands um flag"],
  ["US", "United States", "flag_us united_states usa america american us flag"],
  ["UY", "Uruguay", "flag_uy uruguay uy flag"],
  ["UZ", "Uzbekistan", "flag_uz uzbekistan uz flag"],
  ["VA", "Vatican City", "flag_va vatican_city va flag"],
  ["VC", "Saint Vincent and the Grenadines", "flag_vc saint_vincent_and_the_grenadines vc flag"],
  ["VE", "Venezuela", "flag_ve venezuela ve flag"],
  ["VG", "British Virgin Islands", "flag_vg british_virgin_islands vg flag"],
  ["VI", "US Virgin Islands", "flag_vi us_virgin_islands vi flag"],
  ["VN", "Vietnam", "flag_vn vietnam viet_nam vn flag"],
  ["VU", "Vanuatu", "flag_vu vanuatu vu flag"],
  ["WF", "Wallis and Futuna", "flag_wf wallis_and_futuna wf flag"],
  ["WS", "Samoa", "flag_ws samoa ws flag"],
  ["YE", "Yemen", "flag_ye yemen ye flag"],
  ["YT", "Mayotte", "flag_yt mayotte yt flag"],
  ["ZA", "South Africa", "flag_za south_africa za flag"],
  ["ZM", "Zambia", "flag_zm zambia zm flag"],
  ["ZW", "Zimbabwe", "flag_zw zimbabwe zw flag"],
];

// Regional Indicator Symbol Letter A is U+1F1E6, one per letter after 'A'.
const RI_BASE = 0x1f1e6;
const indicators = (code) => [...code.toUpperCase()].map((c) => String.fromCodePoint(RI_BASE + c.charCodeAt(0) - 65)).join("");

// A subdivision flag is 🏴 plus its ISO 3166-2 code in tag characters, then a cancel tag.
const TAG_BASE = 0xe0000;
const subdivision = (code) => `\u{1f3f4}${[...code].map((c) => String.fromCodePoint(TAG_BASE + c.charCodeAt(0))).join("")}\u{e007f}`;

const SUBDIVISIONS = [
  ["gbeng", "England", "flag_gbeng england english flag"],
  ["gbsct", "Scotland", "flag_gbsct scotland scottish flag"],
  ["gbwls", "Wales", "flag_gbwls wales welsh cymru flag"],
];

// Flags that aren't a place: the picker shows these first.
const GENERIC = [
  ["🏳️", "white_flag surrender flag"],
  ["🏴", "black_flag flag"],
  ["🏁", "checkered_flag chequered finish race flag"],
  ["🚩", "triangular_flag golf flag"],
  ["🏳️‍🌈", "rainbow_flag pride lgbt gay flag"],
  ["🏳️‍⚧️", "transgender_flag trans pride flag"],
  ["🏴‍☠️", "pirate_flag jolly roger flag"],
  ["🎌", "crossed_flags japan celebration flag"],
];

// { emoji, words } like the other picker groups (ui/emoji.js).
export const FLAG_EMOJI = [
  ...GENERIC.map(([emoji, words]) => ({ emoji, words })),
  ...COUNTRIES.map(([code, name, words]) => ({ emoji: indicators(code), words, name })),
  ...SUBDIVISIONS.map(([code, name, words]) => ({ emoji: subdivision(code), words, name })),
];
